package sh.tamga.sdk.support;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * The fingerprint canonicalisation test vectors, loaded from {@code
 * src/test/resources/fingerprint-vectors/fingerprint.json}.
 *
 * <p><b>These were not generated by this SDK, and that is the point.</b> They come from an
 * independent SHA-256 implementation; a fixture an SDK produced can only prove that SDK agrees
 * with itself, which is exactly the failure mode the fingerprint rule exists to prevent across
 * eight ports.
 *
 * <p><b>The file is read as UTF-8 explicitly, and that is not decoration.</b> One vector carries a
 * non-ASCII value, stored as raw UTF-8 bytes rather than as a backslash-u escape. Java's
 * platform default charset is only UTF-8 from Java 18 (JEP 400), this artifact targets Java 11,
 * and CI runs a {@code windows-latest} leg on Temurin 17 -- where the default is the ANSI code
 * page. A reader that took the default would decode that one value as mojibake, hash something
 * else, and fail with a hash mismatch that looks like an algorithm bug. Every other vector is pure
 * ASCII and would pass regardless, so the suite would look like it had caught something specific.
 * {@link #assertDecodedAsUtf8()} turns that failure into a direct statement instead.
 */
public final class FingerprintVectors {

  private static final String RESOURCE = "/fingerprint-vectors/fingerprint.json";

  /** The display placeholder the file uses for the real U+001F separator byte. */
  private static final String SEPARATOR_PLACEHOLDER = "<US>";

  /** The real separator the placeholder stands for: U+001F, one byte. */
  private static final String SEPARATOR = String.valueOf((char) 0x1f);

  private FingerprintVectors() {
  }

  /** One accepted input and the canonical string and fingerprint it must produce. */
  public static final class Vector {
    private final String name;
    private final List<String[]> components;
    private final String canonical;
    private final String fingerprint;

    Vector(String name, List<String[]> components, String canonical, String fingerprint) {
      this.name = name;
      this.components = components;
      this.canonical = canonical;
      this.fingerprint = fingerprint;
    }

    /** The vector's name, used as the parameterized test's display name. */
    public String name() {
      return name;
    }

    /** The labelled components, in the order the file lists them. */
    public List<String[]> components() {
      return Collections.unmodifiableList(components);
    }

    /** The canonical string, with the file's {@code <US>} placeholder replaced by U+001F. */
    public String canonical() {
      return canonical;
    }

    /** The 64-character lowercase hex fingerprint. */
    public String fingerprint() {
      return fingerprint;
    }

    @Override
    public String toString() {
      return name;
    }
  }

  /** One input that must be rejected, and the reason the file gives for it. */
  public static final class Rejected {
    private final String name;
    private final List<String[]> components;
    private final String reason;

    Rejected(String name, List<String[]> components, String reason) {
      this.name = name;
      this.components = components;
      this.reason = reason;
    }

    /** The case's name, used as the parameterized test's display name. */
    public String name() {
      return name;
    }

    /** The labelled components that must be refused. */
    public List<String[]> components() {
      return Collections.unmodifiableList(components);
    }

    /** Why the file says it must be refused. */
    public String reason() {
      return reason;
    }

    @Override
    public String toString() {
      return name;
    }
  }

  /** Every positive vector in the file. */
  public static List<Vector> vectors() {
    JsonNode root = load();
    List<Vector> vectors = new ArrayList<>();
    for (JsonNode node : root.path("vectors")) {
      vectors.add(new Vector(node.path("name").asText(), componentsOf(node),
          node.path("canonical").asText().replace(SEPARATOR_PLACEHOLDER, SEPARATOR),
          node.path("fingerprint").asText()));
    }
    if (vectors.isEmpty()) {
      throw new IllegalStateException("The fingerprint vector file carried no vectors.");
    }
    return vectors;
  }

  /** Every case the file says must be refused. */
  public static List<Rejected> rejected() {
    JsonNode root = load();
    List<Rejected> rejected = new ArrayList<>();
    for (JsonNode node : root.path("rejected")) {
      rejected.add(new Rejected(node.path("name").asText(), componentsOf(node),
          node.path("reason").asText()));
    }
    if (rejected.isEmpty()) {
      throw new IllegalStateException("The fingerprint vector file carried no rejected cases.");
    }
    return rejected;
  }

  /**
   * Throws unless the file's one non-ASCII value decoded to the code points it really holds.
   *
   * <p>Called by the test suite before anything is hashed, so a charset mis-decode reports itself
   * rather than surfacing as an unexplained digest mismatch on one CI leg.
   */
  public static void assertDecodedAsUtf8() {
    String expected = "caf" + (char) 0x00e9;
    for (Vector vector : vectors()) {
      if ("non_ascii_value".equals(vector.name())) {
        String actual = vector.components().get(0)[1];
        if (!expected.equals(actual)) {
          throw new IllegalStateException("The vector file was not decoded as UTF-8: expected the"
              + " non_ascii_value component to read " + describe(expected) + " but it read "
              + describe(actual) + ". A reader using the platform default charset does this on"
              + " Windows before Java 18.");
        }
        return;
      }
    }
    throw new IllegalStateException("The vector file no longer carries the non_ascii_value vector,"
        + " which is the only one that can catch a charset mis-decode.");
  }

  private static String describe(String value) {
    StringBuilder out = new StringBuilder("'").append(value).append("' (");
    for (int i = 0; i < value.length(); i++) {
      if (i > 0) {
        out.append(' ');
      }
      out.append(String.format(java.util.Locale.ROOT, "U+%04X", (int) value.charAt(i)));
    }
    return out.append(')').toString();
  }

  private static List<String[]> componentsOf(JsonNode node) {
    List<String[]> components = new ArrayList<>();
    for (JsonNode pair : node.path("components")) {
      components.add(new String[] {pair.get(0).asText(), pair.get(1).asText()});
    }
    return components;
  }

  /**
   * Reads the file as UTF-8, explicitly.
   *
   * <p>Jackson's own {@code readTree(InputStream)} would sniff the encoding per RFC 8259 and get
   * this right too, but the bytes are decoded here so the charset is stated in the code rather
   * than delegated to a library's auto-detection.
   */
  private static JsonNode load() {
    try (InputStream stream = FingerprintVectors.class.getResourceAsStream(RESOURCE)) {
      if (stream == null) {
        throw new IllegalStateException("Missing test resource: " + RESOURCE);
      }
      java.io.ByteArrayOutputStream buffer = new java.io.ByteArrayOutputStream();
      byte[] chunk = new byte[8192];
      int read;
      while ((read = stream.read(chunk)) != -1) {
        buffer.write(chunk, 0, read);
      }
      return new ObjectMapper().readTree(new String(buffer.toByteArray(), StandardCharsets.UTF_8));
    } catch (IOException e) {
      throw new IllegalStateException("Could not read " + RESOURCE, e);
    }
  }
}
