package sh.tamga.sdk.support;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Map;
import sh.tamga.sdk.model.LicenseScheme;

/**
 * Loads the {@code .machine} fixture corpus in {@code src/test/resources/machine-file-fixtures/}.
 *
 * <p><b>Provenance -- read this before adding anything to that directory.</b> Every file there was
 * produced by the Tamga server's own {@code encode_machine_file}
 * ({@code tamga-api/src/shared/crypto/machine_file.rs}) against throwaway keys, and copied in
 * verbatim. They are NOT generated by this repo and must not be regenerated from it.
 *
 * <p>That rule exists because self-generated fixtures are precisely how this SDK family shipped a
 * broken machine-file reader for two years: every repo tested against a file it had encoded itself,
 * faithfully reproducing its own misreading of the wire format, so CI stayed green while no SDK
 * could open anything the server actually emitted. {@link CheckoutFixture} still builds files with
 * this SDK's own primitives -- that is fine for exercising parse/dispatch wiring, but it can never
 * be evidence that the wire format is understood correctly. Only these files can.
 *
 * <p>If a case is missing, ask for it to be produced from the server's encoder rather than writing
 * one here. Deriving a NEGATIVE case by mutating one of these files is legitimate and is what
 * {@link #withAlg} and {@link #withTamperedEnc} are for: {@code alg} sits outside the signature, so
 * rewriting it models an attacker exactly, and corrupting {@code enc} is what a tampered file is.
 *
 * <p>The manifest is the source of truth for what exists. Iterate it -- never hardcode fixture
 * names -- so new schemes are picked up without touching test code.
 */
public final class MachineFixtures {

  private static final String DIRECTORY = "/machine-file-fixtures/";
  private static final String MANIFEST = DIRECTORY + "manifest.json";
  private static final String BEGIN_MARKER = "-----BEGIN MACHINE FILE-----";
  private static final String END_MARKER = "-----END MACHINE FILE-----";

  private static final ObjectMapper MAPPER = new ObjectMapper();

  /**
   * The server's {@code LicenseScheme} Rust variant names, as they appear in the manifest, mapped
   * onto this SDK's enum. Unknown names throw rather than defaulting: a fixture for a scheme this
   * map does not know about must fail loudly, not be silently verified under the wrong scheme.
   */
  private static final Map<String, LicenseScheme> SCHEMES = Map.of(
      "Ed25519Sign", LicenseScheme.ED25519_SIGN,
      "EcdsaP256Sign", LicenseScheme.ECDSA_P256_SIGN,
      "Rsa2048Pkcs1Sign", LicenseScheme.RSA_2048_PKCS1_SIGN,
      "Rsa2048Pkcs1PssSign", LicenseScheme.RSA_2048_PKCS1_PSS_SIGN,
      "Rsa2048JwtRs256", LicenseScheme.RSA_2048_JWT_RS256);

  private MachineFixtures() {
  }

  /** Every fixture the manifest declares, in manifest order. */
  public static List<Fixture> all() {
    JsonNode manifest = readJson(MANIFEST);
    List<Fixture> fixtures = new ArrayList<>();
    for (Map.Entry<String, JsonNode> entry : manifest.properties()) {
      fixtures.add(new Fixture(entry.getKey(), entry.getValue()));
    }
    if (fixtures.isEmpty()) {
      throw new IllegalStateException("machine-file fixture manifest is empty");
    }
    return fixtures;
  }

  /**
   * Re-wraps a fixture's certificate with a different {@code alg}, leaving {@code enc} and {@code
   * sig} untouched.
   *
   * <p>The signature covers {@code enc} only, so the result is a file with a genuinely valid
   * signature and a rewritten algorithm claim -- exactly what an attacker downgrading a v2 file to
   * v1 would hand over.
   */
  public static String withAlg(Fixture fixture, String alg) {
    ObjectNode certificate = fixture.certificate();
    certificate.put("alg", alg);
    return wrap(certificate);
  }

  /** Re-wraps a fixture's certificate with one character of {@code enc} altered. */
  public static String withTamperedEnc(Fixture fixture) {
    ObjectNode certificate = fixture.certificate();
    String enc = certificate.get("enc").asText();
    // Swap the last character for a different one from the base64 alphabet, so the result stays
    // decodable and the ONLY thing wrong with the file is that the signature no longer matches.
    char last = enc.charAt(enc.length() - 1);
    char replacement = last == 'A' ? 'B' : 'A';
    certificate.put("enc", enc.substring(0, enc.length() - 1) + replacement);
    return wrap(certificate);
  }

  private static String wrap(ObjectNode certificate) {
    byte[] json;
    try {
      json = MAPPER.writeValueAsBytes(certificate);
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
    return BEGIN_MARKER + "\n" + Base64.getEncoder().encodeToString(json) + "\n" + END_MARKER;
  }

  private static JsonNode readJson(String resource) {
    try (InputStream stream = MachineFixtures.class.getResourceAsStream(resource)) {
      if (stream == null) {
        throw new IllegalStateException("Missing fixture resource: " + resource);
      }
      return MAPPER.readTree(stream);
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  private static String readText(String resource) {
    try (InputStream stream = MachineFixtures.class.getResourceAsStream(resource)) {
      if (stream == null) {
        throw new IllegalStateException("Missing fixture resource: " + resource);
      }
      return new String(readAll(stream), StandardCharsets.UTF_8);
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  private static byte[] readAll(InputStream stream) throws IOException {
    java.io.ByteArrayOutputStream buffer = new java.io.ByteArrayOutputStream();
    byte[] chunk = new byte[8192];
    int read;
    while ((read = stream.read(chunk)) != -1) {
      buffer.write(chunk, 0, read);
    }
    return buffer.toByteArray();
  }

  /** One server-produced {@code .machine} file plus the manifest metadata describing it. */
  public static final class Fixture {

    private final String name;
    private final JsonNode entry;

    Fixture(String name, JsonNode entry) {
      this.name = name;
      this.entry = entry;
    }

    /** The manifest key, e.g. {@code rsa_pss_encrypted_valid}. */
    public String name() {
      return name;
    }

    /** The PEM-wrapped file contents, exactly as the server emitted them. */
    public String pem() {
      return readText(DIRECTORY + entry.get("file").asText());
    }

    /** A fresh mutable copy of the inner {@code {enc, sig, alg}} certificate. */
    public ObjectNode certificate() {
      String body = pem().replace(BEGIN_MARKER, "").replace(END_MARKER, "").replaceAll("\\s", "");
      byte[] json = Base64.getDecoder().decode(body);
      try {
        return (ObjectNode) MAPPER.readTree(json);
      } catch (IOException e) {
        throw new UncheckedIOException(e);
      }
    }

    /** The full {@code alg} string the server wrote, e.g. {@code base64+ecdsa-p256+v2}. */
    public String alg() {
      return entry.get("alg").asText();
    }

    /** The license's signing scheme -- what a caller passes in, never read from the file. */
    public LicenseScheme scheme() {
      String raw = entry.get("scheme").asText();
      LicenseScheme scheme = SCHEMES.get(raw);
      if (scheme == null) {
        throw new IllegalStateException("Unmapped fixture scheme '" + raw + "' in " + name);
      }
      return scheme;
    }

    /** The account's public key, in whichever encoding the server distributes for the scheme. */
    public byte[] publicKey() {
      return Base64.getDecoder().decode(publicKeyBase64());
    }

    /**
     * The account's public key as the published base64 STRING -- what a key id is a hash of.
     *
     * <p>Kept separate from {@link #publicKey()} deliberately: the id hashes this string, never
     * the bytes it decodes to.
     */
    public String publicKeyBase64() {
      return entry.get("public_key_b64").asText();
    }

    /** Whether {@code enc} is AES-256-GCM ciphertext rather than plain base64 JSON. */
    public boolean encrypted() {
      return entry.get("encrypted").asBoolean();
    }

    /** Whether {@code enc} is the {@code "<nonce_b64>.<ciphertext_b64>"} two-part form. */
    public boolean encIsDotSeparated() {
      return entry.get("enc_is_dot_separated").asBoolean();
    }

    /** Whether the file's signed {@code exp} claim is in the past. */
    public boolean expired() {
      return entry.get("expired").asBoolean();
    }

    /** The license key an encrypted fixture was sealed with, or {@code null} for a plain one. */
    public String licenseKey() {
      JsonNode node = entry.get("license_key");
      return node == null || node.isNull() ? null : node.asText();
    }

    /** The fingerprint the file was issued for -- HKDF {@code info} for an encrypted fixture. */
    public String fingerprint() {
      return entry.get("fingerprint").asText();
    }

    /**
     * The {@code kid} claim the signed payload carries.
     *
     * <p><b>On a non-Ed25519 fixture this value disagrees with the real server, and must not be
     * used to claim anything about which key signed the file.</b> {@code check_out_machine.rs}
     * selects the SIGNING key by scheme (lines 86-99) but derives the {@code kid} from {@code
     * account.ed25519_public_key} UNCONDITIONALLY (line 127) -- so production emits one kid, the
     * account's Ed25519 one, for all four schemes. This corpus's generator instead derived each
     * kid from that file's own signing key, which is why the manifest carries four distinct kids.
     * Measured, not assumed: all 12 entries satisfy {@code kid == keyId(public_key_b64)}, which
     * the server's own code cannot produce for the RSA and ECDSA rows.
     *
     * <p>What these values legitimately pin is the HASH RULE itself -- see {@code
     * Ed25519KeyIdTest} -- and nothing else. In particular they are not evidence for any
     * kid-to-key lookup on a non-Ed25519 machine file, which is exactly why
     * {@code MachineFile}'s key-set path refuses those files outright.
     */
    public String kid() {
      return entry.get("kid").asText();
    }

    @Override
    public String toString() {
      return name;
    }
  }
}
