package sh.tamga.sdk.support;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

/**
 * The signing-key-id test vectors, loaded from {@code
 * src/test/resources/signing-key-vectors/signing-key-ids.json}.
 *
 * <p><b>These were not generated by this SDK, and that is the point.</b> They come from an
 * independent SHA-256 implementation and were confirmed against {@code tamga-rust}'s own committed
 * vector; a fixture an SDK produced can only prove that SDK agrees with itself, which is precisely
 * how a misread wire format survived in this fleet for two years. The file also carries a
 * <em>negative</em> case -- the id the same key produces if its base64 is decoded before hashing
 * -- because the positive vectors alone do not catch that trap: any implementation that hashes
 * something consistently reproduces its own answer.
 */
public final class SigningKeyVectors {

  private static final String RESOURCE = "/signing-key-vectors/signing-key-ids.json";

  private SigningKeyVectors() {
  }

  /** One published-key/id pair the server's own {@code key_id} produces. */
  public static final class Vector {
    private final String name;
    private final String publicKey;
    private final String keyId;

    Vector(String name, String publicKey, String keyId) {
      this.name = name;
      this.publicKey = publicKey;
      this.keyId = keyId;
    }

    /** The vector's name, used as the parameterized test's display name. */
    public String name() {
      return name;
    }

    /** The public key exactly as the server publishes it: standard base64. */
    public String publicKey() {
      return publicKey;
    }

    /** The 16-character lowercase hex id the server derives from it. */
    public String keyId() {
      return keyId;
    }

    @Override
    public String toString() {
      return name;
    }
  }

  /** Every positive vector in the file. */
  public static List<Vector> vectors() {
    JsonNode root = load();
    List<Vector> vectors = new ArrayList<>();
    for (JsonNode node : root.path("vectors")) {
      vectors.add(new Vector(node.path("name").asText(), node.path("publicKey").asText(),
          node.path("kid").asText()));
    }
    if (vectors.isEmpty()) {
      throw new IllegalStateException("The signing-key vector file carried no vectors.");
    }
    return vectors;
  }

  /** The public key the negative case is built on. */
  public static String negativePublicKey() {
    return load().path("negative").path("publicKey").asText();
  }

  /** The id that key really has -- what a correct implementation must produce. */
  public static String negativeCorrectKeyId() {
    return load().path("negative").path("correctKid").asText();
  }

  /**
   * The id the same key produces if its base64 is decoded to 32 bytes before hashing -- the wrong
   * answer, spelled out so a test can assert the implementation does not produce it.
   */
  public static String negativeKeyIdIfDecodedFirst() {
    return load().path("negative").path("wrongKidIfDecodedFirst").asText();
  }

  private static JsonNode load() {
    try (InputStream stream = SigningKeyVectors.class.getResourceAsStream(RESOURCE)) {
      if (stream == null) {
        throw new IllegalStateException("Missing test resource: " + RESOURCE);
      }
      return new ObjectMapper().readTree(stream);
    } catch (IOException e) {
      throw new IllegalStateException("Could not read " + RESOURCE, e);
    }
  }
}
