package sh.tamga.sdk.checkout;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.stream.Stream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import sh.tamga.sdk.error.TamgaCheckoutException;
import sh.tamga.sdk.model.LicenseScheme;
import sh.tamga.sdk.model.Machine;
import sh.tamga.sdk.support.MachineFixtures;
import sh.tamga.sdk.support.MachineFixtures.Fixture;

/**
 * Verifies {@link MachineFile} against real {@code .machine} files produced by the Tamga server's
 * own encoder -- see {@link MachineFixtures} for provenance and for why nothing here may be
 * generated by this repo.
 *
 * <p>Every case is driven off {@code manifest.json}, so a new scheme or variant added to the
 * fixture directory is picked up with no change to this file.
 *
 * <p><b>Never assert against the wall clock for a non-expired fixture.</b> The valid fixtures carry
 * a real one-hour {@code ttl} and genuinely expire an hour after they were minted; a test that let
 * {@link System#currentTimeMillis()} reach {@code verifyWithClaims} would pass today and fail
 * tomorrow. Timestamps here come from each file's own signed {@code exp} instead.
 */
class MachineFileFixtureTest {

  /**
   * Earlier than any {@code iat} the server can mint, so no fixture is ever expired relative to it.
   * Used when a case is about something other than expiry.
   */
  private static final long BEFORE_ANY_EXPIRY = 0L;

  /** Must equal {@link LicenseFile#CLOCK_SKEW_TOLERANCE_SECONDS} -- pinned by the tests below. */
  private static final long EXPECTED_SKEW_TOLERANCE = 60L;

  static Stream<Fixture> fixtures() {
    return MachineFixtures.all().stream();
  }

  static Stream<Fixture> encryptedFixtures() {
    return MachineFixtures.all().stream().filter(Fixture::encrypted);
  }

  static Stream<Fixture> expiredFixtures() {
    return MachineFixtures.all().stream().filter(Fixture::expired);
  }

  static Stream<Fixture> rsaPkcs1Fixtures() {
    return MachineFixtures.all().stream()
        .filter(fixture -> fixture.scheme() == LicenseScheme.RSA_2048_PKCS1_SIGN);
  }

  private static Machine.MachineWithClaims open(Fixture fixture, long nowUnixSeconds) {
    return MachineFile.parse(fixture.pem()).verifyWithClaims(fixture.scheme(),
        fixture.publicKey(), fixture.licenseKey(), fixture.fingerprint(), nowUnixSeconds);
  }

  /**
   * The corpus must actually cover all four signing schemes and both payload encodings, otherwise
   * a silently-truncated fixture directory would make every parameterized case below vacuous.
   */
  @ParameterizedTest
  @MethodSource("fixtures")
  void manifestDescribesTheFileItPointsAt(Fixture fixture) {
    MachineFile.parse(fixture.pem());

    String enc = fixture.certificate().get("enc").asText();
    assertThat(fixture.certificate().get("alg").asText()).isEqualTo(fixture.alg());
    assertThat(fixture.alg()).endsWith("+v2");
    assertThat(fixture.alg()).startsWith(fixture.encrypted() ? "aes-256-gcm+" : "base64+");
    assertThat(enc.contains(".")).isEqualTo(fixture.encIsDotSeparated());
    assertThat(fixture.encrypted()).isEqualTo(fixture.encIsDotSeparated());
  }

  /**
   * The headline case: a file the server signed verifies under the license's own scheme. Before
   * this fix the ECDSA and RSA fixtures failed here outright -- their public keys are not X.509
   * SPKI, which is all this SDK used to parse.
   */
  @ParameterizedTest
  @MethodSource("fixtures")
  void verifySucceedsForEveryServerProducedFile(Fixture fixture) {
    MachineFile file = MachineFile.parse(fixture.pem());

    assertThat(file.verify(fixture.scheme(), fixture.publicKey())).isTrue();
  }

  /**
   * A plain file decodes and an encrypted one decrypts -- the latter only if {@code enc} is read
   * as two independently base64-encoded halves around a literal {@code '.'}, which is the M2 bug.
   */
  @ParameterizedTest
  @MethodSource("fixtures")
  void verifyWithClaimsReturnsTheMachineAndItsSignedClaims(Fixture fixture) {
    Machine.MachineWithClaims result = open(fixture, BEFORE_ANY_EXPIRY);

    assertThat(result.machine().fingerprint()).isEqualTo(fixture.fingerprint());
    assertThat(result.machine().id()).isNotBlank();
    assertThat(result.claims().keyId()).isEqualTo(fixture.kid());
    assertThat(result.claims().id()).isNotBlank();
    assertThat(result.claims().issuedAt()).isPositive();
    assertThat(result.claims().expiresAt()).isNotNull();
  }

  /**
   * M3: {@code exp} lives inside the signed bytes and must be enforced. An expired file has to
   * come back as its own outcome, not as a signature failure -- a caller that cannot tell the two
   * apart either warns about tampering when a trial merely ended, or offers a renewal for a
   * forgery.
   */
  @ParameterizedTest
  @MethodSource("expiredFixtures")
  void expiredFileIsRejectedAsExpiredNotAsForged(Fixture fixture) {
    long now = System.currentTimeMillis() / 1000L;

    assertThatThrownBy(() -> open(fixture, now))
        .isInstanceOf(TamgaCheckoutException.LicenseFileExpiredException.class);
  }

  /**
   * The same file that was just rejected verifies perfectly at a time before its expiry -- so the
   * rejection above is genuinely about {@code exp} and not about a file this SDK cannot read.
   */
  @ParameterizedTest
  @MethodSource("expiredFixtures")
  void expiredFileStillVerifiesBeforeItsExpiry(Fixture fixture) {
    assertThatCode(() -> open(fixture, BEFORE_ANY_EXPIRY)).doesNotThrowAnyException();
  }

  /**
   * Pins the clock-skew tolerance to the one {@link LicenseFile} already uses. A second, drifting
   * constant would give one of the two file types a different grace period than the other.
   */
  @ParameterizedTest
  @MethodSource("fixtures")
  void expiryToleratesExactlyTheSharedClockSkewAllowanceAndNoMore(Fixture fixture) {
    long expiresAt = open(fixture, BEFORE_ANY_EXPIRY).claims().expiresAt();

    assertThatCode(() -> open(fixture, expiresAt + EXPECTED_SKEW_TOLERANCE))
        .doesNotThrowAnyException();
    assertThatThrownBy(() -> open(fixture, expiresAt + EXPECTED_SKEW_TOLERANCE + 1))
        .isInstanceOf(TamgaCheckoutException.LicenseFileExpiredException.class);
    assertThat(EXPECTED_SKEW_TOLERANCE).isEqualTo(LicenseFile.CLOCK_SKEW_TOLERANCE_SECONDS);
  }

  /**
   * The machine-file key binds BOTH the license key and the fingerprint through HKDF's {@code
   * info}, so a file issued for another machine must fail closed even with the right license key.
   */
  @ParameterizedTest
  @MethodSource("encryptedFixtures")
  void encryptedFileFailsToDecryptUnderTheWrongFingerprint(Fixture fixture) {
    MachineFile file = MachineFile.parse(fixture.pem());

    assertThatThrownBy(() -> file.verifyWithClaims(fixture.scheme(), fixture.publicKey(),
        fixture.licenseKey(), fixture.fingerprint() + "-wrong", BEFORE_ANY_EXPIRY))
        .isInstanceOf(TamgaCheckoutException.DecryptionException.class);
  }

  /** Same, for the license key. */
  @ParameterizedTest
  @MethodSource("encryptedFixtures")
  void encryptedFileFailsToDecryptUnderTheWrongLicenseKey(Fixture fixture) {
    MachineFile file = MachineFile.parse(fixture.pem());

    assertThatThrownBy(() -> file.verifyWithClaims(fixture.scheme(), fixture.publicKey(),
        "TAMGA-NOT-THE-RIGHT-KEY", fixture.fingerprint(), BEFORE_ANY_EXPIRY))
        .isInstanceOf(TamgaCheckoutException.DecryptionException.class);
  }

  /**
   * A tampered {@code enc} must be caught by the signature check, BEFORE anything decodes, splits
   * or decrypts it. The distinct exception type is the evidence: reaching {@code
   * DecryptionException} or {@code OfflineFileFormatException} would mean attacker-controlled bytes
   * were parsed first.
   */
  @ParameterizedTest
  @MethodSource("fixtures")
  void tamperedEncFailsSignatureVerificationBeforeAnyDecode(Fixture fixture) {
    MachineFile file = MachineFile.parse(MachineFixtures.withTamperedEnc(fixture));

    assertThat(file.verify(fixture.scheme(), fixture.publicKey())).isFalse();
    assertThatThrownBy(() -> file.verifyWithClaims(fixture.scheme(), fixture.publicKey(),
        fixture.licenseKey(), fixture.fingerprint(), BEFORE_ANY_EXPIRY))
        .isInstanceOf(TamgaCheckoutException.SignatureVerificationException.class);
  }

  /**
   * M1: the {@code +v2} marker is mandatory. {@code alg} is outside the signature, so stripping it
   * yields a file whose signature is still perfectly valid -- which is exactly why the check has to
   * be explicit. A pre-v2 file carried no signed {@code exp} and derived its key without HKDF.
   */
  @ParameterizedTest
  @MethodSource("fixtures")
  void algWithoutTheV2MarkerIsRejected(Fixture fixture) {
    String downgraded = fixture.alg().substring(0, fixture.alg().lastIndexOf('+'));
    MachineFile file = MachineFile.parse(MachineFixtures.withAlg(fixture, downgraded));

    assertThatThrownBy(() -> file.verify(fixture.scheme(), fixture.publicKey()))
        .isInstanceOf(TamgaCheckoutException.UnsupportedAlgorithmException.class);
  }

  /**
   * The variants a substring {@code contains("...+v2")} test would wave through. Each is a real
   * signature over real bytes with only {@code alg} rewritten, so nothing but a genuine parse
   * stops them.
   */
  @ParameterizedTest
  @MethodSource("fixtures")
  void algThatMerelyResemblesV2IsRejected(Fixture fixture) {
    String suffix = fixture.alg().substring(fixture.alg().indexOf('+') + 1,
        fixture.alg().lastIndexOf('+'));
    String[] impostors = {
        fixture.alg().replace("+v2", "+v3"),
        fixture.alg() + "junk",
        "x" + fixture.alg(),
        fixture.alg().replace("+v2", "+v2+v2"),
        suffix + "+v2",
        "base64+" + suffix,
        "+" + suffix + "+v2",
        fixture.alg() + "+",
    };

    for (String impostor : impostors) {
      MachineFile file = MachineFile.parse(MachineFixtures.withAlg(fixture, impostor));
      assertThatThrownBy(() -> file.verify(fixture.scheme(), fixture.publicKey()))
          .describedAs("alg '%s' must be rejected", impostor)
          .isInstanceOf(TamgaCheckoutException.class);
    }
  }

  /**
   * The signing suffix has to agree with the scheme the caller supplied. Both halves of the
   * compound string carry hyphens ({@code aes-256-gcm}, {@code rsa-pss-sha256}), so a parser that
   * splits on the wrong {@code +} passes on {@code ed25519} and quietly mismatches here.
   */
  @ParameterizedTest
  @MethodSource("fixtures")
  void algDeclaringAnotherSchemesSuffixIsRejected(Fixture fixture) {
    String encoding = fixture.alg().substring(0, fixture.alg().indexOf('+'));
    String actualSuffix = fixture.alg().substring(fixture.alg().indexOf('+') + 1,
        fixture.alg().lastIndexOf('+'));
    String otherSuffix = "ed25519".equals(actualSuffix) ? "rsa-pss-sha256" : "ed25519";
    MachineFile file =
        MachineFile.parse(MachineFixtures.withAlg(fixture, encoding + "+" + otherSuffix + "+v2"));

    assertThatThrownBy(() -> file.verify(fixture.scheme(), fixture.publicKey()))
        .isInstanceOf(TamgaCheckoutException.UnsupportedAlgorithmException.class);
  }

  /**
   * The proof that the caller's scheme is authoritative and {@code alg} is only ever a cross-check:
   * the server emits {@code rsa-sha256} for {@code RSA_2048_PKCS1_SIGN} and for {@code
   * RSA_2048_JWT_RS256} alike, so these exact bytes must verify under one and be refused outright
   * under the other.
   */
  @ParameterizedTest
  @MethodSource("rsaPkcs1Fixtures")
  void identicalRsaSha256FileVerifiesUnderPkcs1AndIsRefusedUnderJwtRs256(Fixture fixture) {
    MachineFile file = MachineFile.parse(fixture.pem());
    assertThat(fixture.alg()).contains("+rsa-sha256+");

    assertThat(file.verify(LicenseScheme.RSA_2048_PKCS1_SIGN, fixture.publicKey())).isTrue();
    assertThatThrownBy(() -> file.verify(LicenseScheme.RSA_2048_JWT_RS256, fixture.publicKey()))
        .isInstanceOf(TamgaCheckoutException.SchemeNotSupportedException.class);
  }
}
